# Generated by Django 4.2.4 on 2023-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_pr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_s',
            name='under_service',
        ),
        migrations.AddField(
            model_name='booking_s',
            name='service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='selectcategory',
            name='select_category',
            field=models.CharField(max_length=500),
        ),
        migrations.DeleteModel(
            name='UnderService',
        ),
    ]
