# Generated by Django 4.2.4 on 2023-08-17 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services_pr', '0002_remove_booking_s_under_service_booking_s_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectcategory',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='selectcategory',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
