# Generated by Django 4.2.4 on 2023-08-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restourant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_restourant',
            name='image_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=350),
        ),
    ]
